
package GUI;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *  ThumbPanel Are showing images 
 * 
 */
public class ThumbPanel extends javax.swing.JPanel {

    /** Creates new form ThumbPanel */
    
    private int lblWidth=131;
    private int lblHeight=123;
    
    
    public ThumbPanel() {
        initComponents();
    }

    public void setImage1(File imgFile)
    {
//     pnl1.removeAll();
//     myPanel mypanel=new myPanel(imgFile,pnl1.getWidth(),pnl1.getHeight());
//     pnl1.add(mypanel);
      ImageIcon icon=new ImageIcon(imgFile.getAbsolutePath());
      
      lblImg1.setIcon(resize(icon, lblWidth, lblHeight));
    }
    
    public void setImage2(File imgFile)
    {
      ImageIcon icon=new ImageIcon(imgFile.getAbsolutePath());     
      lblImg2.setIcon(resize(icon, lblWidth, lblHeight)); 
    }
    
    public void setImage3(File imgFile)
    {
      ImageIcon icon=new ImageIcon(imgFile.getAbsolutePath());     
      lblImg3.setIcon(resize(icon, lblWidth, lblHeight)); 
    }
    
    public void setImage4(File imgFile)
    {
      ImageIcon icon=new ImageIcon(imgFile.getAbsolutePath());
      
      lblImg4.setIcon(resize(icon, lblWidth, lblHeight)); 
    }
    
    public ImageIcon resize(ImageIcon icon,int width,int height)
    {
        try{
        Image img = icon.getImage();
        Image newimg = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        }catch(Exception e){}
        return icon;     
    }
    

    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg1 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        lblImg3 = new javax.swing.JLabel();
        lblImg4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(631, 150));

        lblImg1.setBackground(new java.awt.Color(255, 255, 255));
        lblImg1.setForeground(new java.awt.Color(255, 255, 255));
        lblImg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImg2.setBackground(new java.awt.Color(255, 255, 255));
        lblImg2.setForeground(new java.awt.Color(255, 255, 255));
        lblImg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImg3.setBackground(new java.awt.Color(255, 255, 255));
        lblImg3.setForeground(new java.awt.Color(255, 255, 255));
        lblImg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImg4.setBackground(new java.awt.Color(255, 255, 255));
        lblImg4.setForeground(new java.awt.Color(255, 255, 255));
        lblImg4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(lblImg3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(lblImg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(lblImg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblImg4;
    // End of variables declaration//GEN-END:variables
}
